# Generated by Django 4.2.7 on 2023-11-18 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated', models.DateField()),
                ('TennisId', models.CharField(max_length=100)),
                ('StandardGivenName', models.CharField(max_length=64)),
                ('StandardFamilyName', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated', models.DateField()),
                ('RankingID', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=128)),
                ('RankingType', models.CharField(max_length=64)),
                ('Gender', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RankingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=32)),
                ('SortOrder', models.IntegerField()),
                ('Result', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('RankingItemsCode', models.IntegerField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.person')),
                ('Ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.ranking')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='RankingItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.rankingitem'),
        ),
    ]
