# Generated by Django 4.2.7 on 2023-11-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_ranking_rankingitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='RankingItems',
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='Rank',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='RankingItemsCode',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='Result',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='SortOrder',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='rankingitem',
            name='Type',
            field=models.CharField(default='Roll Over', max_length=32),
        ),
    ]
