# Generated by Django 4.2.7 on 2023-11-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_ranking_rankingitems_alter_rankingitem_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='RankingItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.rankingitem'),
        ),
    ]
