# Generated by Django 4.2.7 on 2023-11-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_ranking_rankingitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='RankingItems',
            field=models.ManyToManyField(blank=True, related_name='rankings', to='quickstart.rankingitem'),
        ),
    ]
