# Generated by Django 4.2.7 on 2023-11-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_ranking_rankingitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Challenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_challenged', to='quickstart.rankingitem')),
                ('Challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_as_challenger', to='quickstart.rankingitem')),
            ],
        ),
    ]
