# Generated by Django 4.2.7 on 2023-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingitem',
            name='BeingChallenged',
            field=models.ManyToManyField(related_name='challenges_as_challenged', to='quickstart.challenge'),
        ),
        migrations.AddField(
            model_name='rankingitem',
            name='Challenging',
            field=models.ManyToManyField(related_name='challenges_as_challenger', to='quickstart.challenge'),
        ),
    ]
