# Generated by Django 4.2.7 on 2023-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_rankingitem_beingchallenged_rankingitem_challenging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='Updated',
        ),
        migrations.AlterField(
            model_name='person',
            name='Updated',
            field=models.DateTimeField(),
        ),
    ]
