# Generated by Django 4.2.7 on 2023-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_remove_ranking_updated_alter_person_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='Message',
            field=models.CharField(default='Mensagem de desafi', max_length=255),
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Concluido', 'Concluido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10),
        ),
    ]
