# Generated by Django 4.2.7 on 2023-11-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_challenge_message_challenge_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='status',
            new_name='Status',
        ),
    ]
