# Generated by Django 4.2.7 on 2023-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_rename_status_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='Score',
            field=models.CharField(default='0-0 0-0', max_length=255),
        ),
    ]
